### ISSUE TITLE
Some tags not available

### ISSUE THREAD

**Issue by parkmino** [CDrummond/cantata#1193]
Please find the attached file of which tag is not available in Cantata.
Other MPD clients has no problem.

[02. 이진아 - RANDOM.flac.tar.gz](https://github.com/CDrummond/cantata/files/1701390/02.-.RANDOM.flac.tar.gz)

**Comment by parkmino** [comment]
Seems duplicate of #1194 and this tag might has been edited in Cantata

**Comment by CDrummond** [comment]
I've just added this to my MPD instance, and refreshed in Cantata - and it shows just fine.

**Comment by parkmino** [comment]
Yes, MPD instance is OK ,however non-MPD file can be added to playqueue showing no tags.
As far as I remember, I edited this tag in Cantata.

**Comment by CDrummond** [comment]
Looks like an issue with TagLib. I've just tried taglib/master, and it now works for me.

See https://github.com/taglib/taglib/issues/788

As to editing the tags with Cantata, with the non-master taglib this fails for me. And the reason would be the same as the load error. All I can think is to bundle a copy of taglib/master with Cantata.

**Comment by parkmino** [comment]
Hmm... It is hard for the novice like me to try this solution.
I compiled the taglib as the following link, still but the problem occurs.

https://github.com/taglib/taglib/blob/master/INSTALL.md

**Comment by CDrummond** [comment]
Well, I've **only** tested with your example file (linked above). When building taglib you **must** ensure to build shared libraries - pass `-DBUILD_SHARED_LIBS=ON` to taglib's cmake.

I also hacked my system by removing `/usr/lib/x86_64-linux-gnu/libtag.so.1.17.0` (which was the original shared library) and sym linking to my newly built version. `ln -s /usr/local/lib/libtag.so.1.17.0 /usr/lib/x86_64-linux-gnu/libtag.so.1.17.0`

**Comment by parkmino** [comment]
I followed your instruction and this issue is resolved! But not #1194

**Comment by CDrummond** [comment]
Well, its not resolved - as there's still an issue. I'm debating whether to just leave it as is (and wait for a new taglib release), or to bundle taglib with Cantata.

**Comment by CDrummond** [comment]
Closing - this is a taglib issue, and I don't feel like bundling a copy.
