### ISSUE TITLE
Searching fails, finds not all tracks

### ISSUE THREAD

**Issue by vibee** [CDrummond/cantata#712]
I just had 2 issues related to the search function.

1. Search for "niemand hat"
There is an album, whose name is "Niemand hat die Absicht auf Tour zu gehen". It cotains 16 properly tagged tracks, all of those have been successfully read by mpd. 
If I perdorm the search "niemand hat", cantata finds this album (no matter album or artist view), but surprisingly only one track (the first one) is displayed. Also, if I search for the album's artist, it only find this single track and doesn't display the other 15 ones. Needed to add it via Folders view.

2. Search for "K-Def"
I got some albums of an artist named K-Def. If I search for "K-Def", cantata finds really many albums and tracks, all of those do not contain the string "K-Def" anywhere. For instance, it finds:
Artist: Devoye
Album: Folkes
Genre: Hip-Hop
Track name: K(no)w I  Cant Stand It
From that album, it only finds this single track (there are more than one). The file has no other tags, no comment or anything. Obviously canata's search returns garbage. And surprisingly, it doesn't find the albums from K-Def (what I was searching for :). 
If I search for the album title of the K-Def album (it's also properly tagged), it only finds one track of 12. I need to add it via Folder view again.

---

I think this issue is only related to newer versions of cantata, e.g. was not there in last stable. That's just 2 examples which occured within 5 minutes. For reproducing that bug, if you need some files, I could at least send you file and tag details.

**Comment by CDrummond** [comment]
Which version of cantata? 1.5.2 or git/master?

**Comment by vibee** [comment]
git/master

**Comment by CDrummond** [comment]
Can you:

1. Stop Cantata
2. delete all sql files in ~/.local/share/cantata/library
3. Start Cantata from the commandline as follows:

CANTATA_DEBUG=0x00040000 cantata

4. Close Cantata after it has started and re-loaded the library
5. Copy ~/.cache/cantata/cantata.log here - or provide a link to it

**Comment by vibee** [comment]
Can I send you the file via e-mail? I don't like to publish all the details in the log file.

**Comment by CDrummond** [comment]
Sure - my address is in the README

**Comment by CDrummond** [comment]
At the moment I only care if has lines like "Failed to create FTS table"

**Comment by vibee** [comment]
Nope, nothing in there.

**Comment by CDrummond** [comment]
Can you install sqlitebrowser? If so, use this to open the .sql file in ~/.local/share/cantata/library/

When started, in the 'Execute SQL' tab try entering something like:

SELECT * FROM songs INNER JOIN songs_fts AS fts ON songs.ROWID = fts.ROWID WHERE songs_fts match 'Maid*' AND artistId = 'Iron Maiden' AND albumId = 'Killers'

Replace 'Maid*' with your search string (add an asterisk after each word), 'Iron Maiden' with the artsit (or AlbumArtist) of the album, and 'Killers' with the album name.

This is the search Cantata does to get the tracks from 'Iron Maiden/Killers' that match the string 'Maid*' - obviously all tracks in this example.

**Comment by vibee** [comment]
SELECT * FROM songs INNER JOIN songs_fts AS fts ON songs.ROWID = fts.ROWID WHERE songs_fts match 'K-Def*' AND artistId = 'K-DEF' AND albumId = 'Back To The Beat'

does not return anything, but

SELECT * FROM songs INNER JOIN songs_fts AS fts ON songs.ROWID = fts.ROWID WHERE songs_fts match 'K-*' AND artistId = 'K-DEF' AND albumId = 'Back To The Beat'

return all tracks from that album 

---

SELECT * FROM songs INNER JOIN songs_fts AS fts ON songs.ROWID = fts.ROWID WHERE songs_fts match 'Niemand*' AND artistId = 'Veedel Kaztro, Gold Roger, Johnny Rakete' AND albumId = 'Niemand hat die Absicht auf Tour zu gehen'

return the first track of that album only, however

SELECT * FROM songs INNER JOIN songs_fts AS fts ON songs.ROWID = fts.ROWID WHERE artistId = 'Veedel Kaztro, Gold Roger, Johnny Rakete' AND albumId = 'Niemand hat die Absicht auf Tour zu gehen'

lists all the tracks.

---

I guess that what is wrong here, is that the search string is parsed in the songs_fts field only. It should be parsed in OR-combined fields for album title, artist name, track title, right?

**Comment by vibee** [comment]
Did you perhaps change the search semantics recently?

**Comment by CDrummond** [comment]
Well originally it as doing an OR - so 'Iron Abba' would find Iron Maiden and Abba. But this was changed to an AND - so that only songs with Iron AND Abba would be found.

Your first example of each SELECT is that ONLY one that is doing a search. The others are simply listing items that match the IDs. However, for a search you want the IDs and the search to march.

Can you post the output of SELECT * FROM songs INNER JOIN songs_fts AS fts ON songs.ROWID = fts.ROWID WHERE songs_fts match 'K-*' AND artistId = 'K-DEF' AND albumId = 'Back To The Beat'

**Comment by vibee** [comment]
Returns all the 12 tracks.

**Comment by vibee** [comment]
I agree to the changes you states in your first sentence. They make sense.

For my second case ("Niemand hat ..."), the problem seems to be that the album title is "Niemand hat ..." and the first song's title equals the album title (also "Niemand hat ..."). cantata, just like sqlitebrowser, then only lists this single song from the album.

**Comment by vibee** [comment]
Btw, I just observed that if I search for album titles, cantata only searches the song title.. If I search for an album title which does not contain a song of the same name, cantata simply doesn't find it.

**Comment by CDrummond** [comment]
D'oh!!! Realised my STUPID mistake!

In Cantata's main songs table there is an album and albumId field. The reason being so as to differentiate between two albums with the same album name - but different music brainz album id. (e.g. for re-releases, etc). Now for my collection I have no duplicate albums, and for Cantata stores the album name as albumId. To save space, in this case where albumId==album I dont store the string again. Now, when the songs_fts table is created, I'm only copying the 'album' string - which is empty if albumId==album!

**Comment by CDrummond** [comment]
Should be fixed now. But you will need to delete the SQL file in  ~/.local/share/cantata/library and restart. This should be automatic - as I increased the schema version, but is not working at the moment. I'm looking into this now.

**Comment by vibee** [comment]
Great, thanks. The only thing that is not fixed yet is the case where I search for "K-Def" and find lots of garbage, but not the music from artist K-Def. Search for "K-" works, then I find the music. Maybe some struggle with hyphens?

**Comment by CDrummond** [comment]
Ah, needed to surround each string in quotes. Please update and try again.

**Comment by vibee** [comment]
As far as I can see, the problem is fixed. Thanks :+1:

**Comment by CDrummond** [comment]
Thanks for the confirmation.
